# Generated by Django 5.1.1 on 2025-05-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminargroup',
            old_name='student',
            new_name='students',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='seminargroup',
            unique_together={('seminar', 'group_number')},
        ),
    ]
