# Generated by Django 5.1.1 on 2025-05-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_student_seminargroup_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='check_number',
            field=models.CharField(default='11233468', max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminar',
            name='eligible_programs',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('BScEd', 'Bachelor of Science with Education'), ('BAEd', 'Bachelor of Arts with Education'), ('BEdSci', 'Bachelor of Education in Science'), ('BEdArts', 'Bachelor of Education in Arts')], default='Bachelor of science with education', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
