# Generated by Django 5.1.1 on 2025-06-16 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_seminarregistration_registration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminargroup',
            name='marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='seminargroup',
            name='seminar_file',
            field=models.FileField(blank=True, null=True, upload_to='seminar_work/'),
        ),
        migrations.AddField(
            model_name='seminargroup',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_groups', to='base.student'),
        ),
    ]
