# Generated by Django 5.1.1 on 2025-07-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_seminargroup_marks_seminargroup_seminar_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminargroup',
            name='seminar_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
