# Generated by Django 5.1.1 on 2025-07-19 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_seminargroup_seminar_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminargroup',
            name='group_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_groups', to='base.student'),
        ),
    ]
